#!/bin/bash

if [ -f "~/aliases.local" ]; then
	source ~/aliases.local
fi 

alias mux='tmuxinator'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias r='ranger'

# enable color support of ls and also add handy aliases
alias ls='ls --color=auto --group-directories-first'
alias la='ls -A --color=auto --group-directories-first'
alias l='ls -CF --color=auto --group-directories-first'
alias ll="ls -lhA --color=auto --group-directories-first"
alias sl="ls --color=auto --group-directories-first"
alias lsl="ls -lhFA --color=auto --group-directories-first | less"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some folder shortcuts 
alias vrc='vim ~/.vimrc'
alias brc='vim ~/.bashrc'

# Various
alias cd..="cd .."
alias rd="rmdir"
alias du="du -ach | sort -h"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..6='cd ../../../../../..'
alias ..9='cd ../../../../../../../../..'

alias gs="git status"
alias gd="git diff"
alias gl="git log --branches --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gc="git commit"
alias gci="git commit --interactive"
alias gau="git add --update"
alias gai="git add --interactive"

# grepping by using gp after command
alias gp='| grep -i'

# Process information
alias ps="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

alias top=htop

# Docker
dcleanup(){
	docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
	docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

alias gr=gradle
alias gralde=gradle
