#!/bin/bash

# fasd shortcuts
alias v='vim `f $1*`'

alias s-aliases="source ~/dotfiles/aliases"
alias c-aliases="vim ~/dotfiles/aliases; s-aliases; echo aliases auto-sourced"
alias c-kitty="vim ~/.config/kitty/kitty.conf"
alias c-vim="vim ~/.vimrc"
alias c-bash="vim ~/.bashrc; echo .bashrc auto-sourced"
alias c-ssh="vim ~/.ssh/config"
alias c-ranger="ranger ~/.config/ranger/"
alias c-git-local="git config -e --local"
alias c-git-global="git config -e --global"
alias c-git-system="git config -e --system"

alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias r='source ranger' # by sourcing ranger, when we quit ranger, we are left in the active directory, instead of the beginning directory
alias m="make"

# enable color support of ls and also add handy aliases
alias ls='ls -h --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ll="ls -lhA --group-directories-first --color=auto"
alias sl="ls"
alias lsl="ls -lhFA --color=auto | less"

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Various
function c() {
  cd $1;
  ls;
}
alias cd="c"
alias cd..="cd .."
alias rd="rmdir"
alias du="du -ach | sort -h"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'

alias gs="git status"
alias gl="git log --branches --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gc="git commit"
alias gci="git commit --interactive"
alias gai="git add --interactive"
alias gcod="git checkout develop"
alias gd="git diff --ignore-all-space --ignore-blank-lines"

# grepping by using gp after command
alias gp='| grep -i'

# Process information
alias ps="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

alias top=htop
